USE DATABASE USER_DB_COBRA;
CREATE SCHEMA IF NOT EXISTS DASHBOARD;
USE SCHEMA DASHBOARD;

CREATE OR REPLACE VIEW DASHBOARD.NETFLIX_CATALOG AS
SELECT * FROM ANALYTICS.FACT_NETFLIX_CATALOG;

CREATE OR REPLACE VIEW DASHBOARD.TMDB_TRENDING_SNAPSHOT AS
SELECT * FROM ANALYTICS.FACT_TMDB_TRENDING_SNAPSHOT;

CREATE OR REPLACE VIEW DASHBOARD.GENRE_GAP_ANALYSIS AS
SELECT * FROM ANALYTICS.MART_GENRE_GAP_ANALYSIS;

CREATE OR REPLACE VIEW DASHBOARD.KPIS_DAILY AS
SELECT * FROM ANALYTICS.MART_KPIS_DAILY;


CREATE OR REPLACE VIEW DASHBOARD.DIM_GENRE AS
SELECT * FROM ANALYTICS.DIM_GENRE;

CREATE OR REPLACE VIEW DASHBOARD.DIM_TITLE AS
SELECT * FROM ANALYTICS.DIM_TITLE;