USE USER_DB_COBRA;
USE SCHEMA RAW;

-- Load raw data directly, no transformations (dbt handles cleaning)
COPY INTO USER_DB_COBRA.RAW.NETFLIX_TITLES
FROM @USER_DB_COBRA.RAW.NETFLIX_STAGE/netflix_titles.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- Verify
SELECT COUNT(*) FROM USER_DB_COBRA.RAW.NETFLIX_TITLES;
SELECT * FROM USER_DB_COBRA.RAW.NETFLIX_TITLES LIMIT 5;
SELECT COUNT(*) FROM USER_DB_COBRA.RAW.NETFLIX_TITLES 
WHERE show_id IS NULL OR title IS NULL;